AWSTemplateFormatVersion: '2010-09-09'
Description: Load Balancer

Parameters:
  PublicSubnet1:
    Type: String
    Description: The ID of the first public subnet
  PublicSubnet2:
    Type: String
    Description: The ID of the second public subnet
  SecurityGroup:
    Type: String
    Description: The ID of the security group

Resources:
  LoadBalancer:
    Type: 'AWS::ElasticLoadBalancing::LoadBalancer'
    Properties:
      LoadBalancerName: veris-loadbalancer
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      SecurityGroups:
        - !Ref SecurityGroup
      Listeners:
        - LoadBalancerPort: '80'
          InstancePort: '80'
          Protocol: 'HTTP'


  ALB:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Name: veris-alb
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      SecurityGroups:
        - !Ref SecurityGroup
      Scheme: internet-facing
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: '60'

Outputs:
  LoadBalancerDNS:
    Description: Load Balancer DNS
    Value: !GetAtt LoadBalancer.DNSName

  ALBDNS:
    Description: ALB DNS
    Value: !GetAtt ALB.DNSName
