AWSTemplateFormatVersion: '2010-09-09'
Description: Security Group to allow SSH, HTTP, and HTTPS traffic

Parameters:
  VPC:
    Type: String
    Description: VPC ID to associate with the security group

Resources:
  SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow SSH, HTTP, and HTTPS traffic
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: '0.0.0.0/0'
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: '0.0.0.0/0'
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: '0.0.0.0/0'

Outputs:
  SecurityGroupId:
    Description: Security Group ID
    Value: !Ref SecurityGroup
